apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-logic-service-blue
  labels:
    app: aggregation-logic-service
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregation-logic-service
      version: blue
  template:
    metadata:
      labels:
        app: aggregation-logic-service
        version: blue
    spec:
      containers:
        - name: aggregation-logic-service
          image: gcr.io/YOUR_PROJECT_ID/aggregation-logic-service:blue
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/aggregation-logic-service/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/aggregation-logic-service/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-logic-service-green
  labels:
    app: aggregation-logic-service
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aggregation-logic-service
      version: green
  template:
    metadata:
      labels:
        app: aggregation-logic-service
        version: green
    spec:
      containers:
        - name: aggregation-logic-service
          image: gcr.io/YOUR_PROJECT_ID/aggregation-logic-service:green
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/aggregation-logic-service/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/aggregation-logic-service/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
